// Resource ids for doctor-valkyrie.
#pragma once

#define IDB_DOCTOR_HEADER 101
#define IDB_DOCTOR_UNKNOWN_HEADER 102
#define IDR_DOCTOR_RULES 201
#define IDR_CRASHINFO_RULES 202
#define IDR_DOCTOR_RULES_ES 203
#define IDR_CRASHINFO_RULES_ES 204
#define IDB_DOCTOR_EAGLE 301
#define IDB_DOCTOR_EAGLE_GRAY 302
#define IDB_DOCTOR_SSMP 303
#define IDB_DOCTOR_SSMP_GRAY 304
