# Public build only: produces ASIs in build/ and never installs into a game.
# Build the independent SP-RP client ASIs.
#
# An ASI is a DLL the game's loader picks up by extension, so this is an
# ordinary 32 bit DLL build - 32 bit because San Andreas is, and there is no
# version of this that runs in a 64 bit process.
#
#   build.ps1              build a development build (logs, fast compile) into build/
#   build.ps1 -Clean       throw the build away first
#   build.ps1 -Release     build a hardened build for shipping - see below
#
# Development is the default because it is what every local test run needs:
# a log file to read when something goes wrong. -Release is the opt-in,
# reserved for builds that actually leave this machine (a Valkyrie-style
# public release). Do not flip that default - a development session with no
# diagnostics is a session where the next crash has to be re-diagnosed blind.
param(
    [string] $OnlyTarget,
    [switch] $Clean,
    [switch] $Release
)

$ErrorActionPreference = "Stop"

$root    = Split-Path -Parent $MyInvocation.MyCommand.Path
$build   = Join-Path $root "build"
# Public Map baseline and current Doctor release.
$version = "0.2.0"
$mapVersion = "0.2.0"
$doctorVersion = "0.3.2"

# Visual Studio 2019 Build Tools. Found rather than hardcoded, because the
# toolset version in the path changes with every update.
$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) {
    throw "Visual Studio Build Tools are not installed - no vswhere at $vswhere"
}

$vsPath = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
if (-not $vsPath) {
    # The C++ workload is what actually matters; fall back to any install and
    # let vcvarsall complain if the compiler really is missing.
    $vsPath = & $vswhere -latest -products * -property installationPath
}
if (-not $vsPath) {
    throw "No Visual Studio installation with a C++ compiler"
}

$vcvars = Join-Path $vsPath "VC\Auxiliary\Build\vcvarsall.bat"
if (-not (Test-Path $vcvars)) {
    throw "No vcvarsall.bat at $vcvars"
}

if ($Clean -and (Test-Path $build)) {
    Remove-Item -Recurse -Force $build
}
if (-not (Test-Path $build)) {
    New-Item -ItemType Directory -Path $build | Out-Null
}

# The version goes through a generated header rather than a /D on the command
# line. A quoted string define has to survive PowerShell, then cmd, then the
# compiler's own parsing, and it does not reliably survive all three.
$versionHeader = Join-Path $root "valkyrie-core\src\version.h"
@"
// Generated by build.ps1. Do not edit - your change will be overwritten on the
// next build. The versions live at the top of build.ps1.
#pragma once

#define SPRP_SUITE_VERSION "$version"
#define SPRP_BLIPS_VERSION SPRP_SUITE_VERSION
#define VALKYRIE_MAP_VERSION "$mapVersion"
#define DOCTOR_VALKYRIE_VERSION "$doctorVersion"
"@ | Set-Content -Path $versionHeader -Encoding ASCII

# /MT so the plugin does not need a Visual C++ runtime the player has not got.
# The whole point is that it works on someone else's machine.
#
# There is no third party code here any more. Dear ImGui was vendored for a
# while, to draw the map panel over Direct3D the way Project Eagle does its own
# interface - but Eagle is already doing exactly that, and two mods cannot both
# be last in the same hook without one of them losing or the pair of them
# calling each other until the game dies. The panel draws with the game's own
# font and boxes instead, which nothing else is competing for.
# -Release only: /DNDEBUG strips every logfile::Line call and its format
# strings from the binary at compile time (the inline no-ops in log.h mean
# the compiler never emits the string literals, so they cannot be read from
# a shipped ASI); /GL enables whole-program optimisation and /Gy emits one
# function per COMDAT so the linker can discard any that are entirely
# inlined away; /LTCG on the /link line activates link-time code generation
# to finish what /GL started - cross-TU inlining, dead-function elimination,
# better layout. None of that belongs in a development build: it is slower
# to compile and it is the diagnostics themselves being thrown away, and
# development is exactly when they get read.
$releaseFlags = @("/GL", "/Gy", "/DNDEBUG")
$flags = (@(
    "/nologo", "/std:c++17", "/EHsc", "/O2", "/MT", "/W4", "/WX", "/utf-8",
    "/DWIN32_LEAN_AND_MEAN", "/DNOMINMAX", "/D_CRT_SECURE_NO_WARNINGS"
) + $(if ($Release) { $releaseFlags }) + @("/LD")) -join " "
$linkFlags = if ($Release) { "/LTCG" } else { "" }

Write-Host "[build] $(if ($Release) { 'RELEASE (hardened, no diagnostics)' } else { 'development (with diagnostics)' })" -ForegroundColor $(if ($Release) { "Yellow" } else { "Cyan" })

$targets = @(
    @{ Name = "valkyrie-map"; Module = "valkyrie-map"; ModuleSources = @("main_map.cpp", "mapzoom.cpp"); CoreSources = @("game.cpp", "switches.cpp", "log.cpp"); Defines = @() },
    @{ Name = "doctor-valkyrie"; Module = "doctor-valkyrie"; ModuleSources = @("main_doctor.cpp", "doctor.cpp", "doctorlist.cpp", "cleowatch.cpp", "reportpaths.cpp", "crashwindow.cpp"); CoreSources = @("log.cpp"); Defines = @() }
)
if ($OnlyTarget -and $OnlyTarget -notin $targets.Name) { throw "Unknown public target: $OnlyTarget" }

$outputs = @()
foreach ($targetSpec in $targets) {
    if ($OnlyTarget -and $targetSpec.Name -ne $OnlyTarget) { continue }
    $target = $targetSpec
    $name = $target.Name
    $obj = Join-Path $build "obj\$name"
    New-Item -ItemType Directory -Path $obj -Force | Out-Null

    $sources = @($target.ModuleSources | ForEach-Object { "$($target.Module)\src\$_" })
    $sources += @($target.CoreSources | ForEach-Object { "valkyrie-core\src\$_" })
    $defines = $target.Defines | ForEach-Object { "/D$_" }
    $relativeOut = "build\$name.asi"
    $relativeObj = "build\obj\$name\"
    $libraries = if ($name -eq "doctor-valkyrie") {
        "user32.lib gdi32.lib shell32.lib advapi32.lib"
    } else {
        ""
    }
    # doctor-valkyrie's banner is a Win32 resource. Compile it first and pass
    # the resulting .res to the linker, keeping the image inside the ASI.
    $resources = ""
    if ($name -eq "doctor-valkyrie") {
        $resourceOut = "$relativeObj" + "doctor-valkyrie.res"
        $resources = "$resourceOut"
        $resourceCommand = "rc /nologo /Ivalkyrie-core\src /I$($target.Module)\src /fo$resourceOut $($target.Module)\src\doctor-valkyrie.rc && "
    } else {
        $resourceCommand = ""
    }
    $cmd = "`"$vcvars`" x86 >nul && cd /d `"$root`" && $resourceCommand" +
           "cl $flags /Ivalkyrie-core\src /I$($target.Module)\src $($defines -join ' ') $($sources -join ' ') $resources /Fo$relativeObj /Fe$relativeOut /link /SUBSYSTEM:WINDOWS $linkFlags $libraries"

    $shownVersion = switch ($name) {
        "valkyrie-map"     { $mapVersion }
        "doctor-valkyrie"  { $doctorVersion }
        default            { $version }
    }
    Write-Host "[build] compiling $name $shownVersion (x86)" -ForegroundColor Green
    cmd /c $cmd
    if ($LASTEXITCODE -ne 0) {
        throw "$name compile failed"
    }

    # An ASI loaded into a 64 bit process does nothing and says nothing about
    # why, so check every output rather than trust the toolchain environment.
    $out = Join-Path $build "$name.asi"
    $bytes = [IO.File]::ReadAllBytes($out)
    $peAt = [BitConverter]::ToInt32($bytes, 0x3C)
    $machine = [BitConverter]::ToUInt16($bytes, $peAt + 4)
    if ($machine -ne 0x14C) {
        throw ("$name has machine 0x{0:X4}, wanted x86 0x014C" -f $machine)
    }

    $outputs += $out
    Write-Host "[build] $out  ($((Get-Item $out).Length) bytes, x86)" -ForegroundColor Green
}

